import requests
import json
from ..config import settings

def send_slack_notification(message: str, username: str = "TrendForgeAI Bot", icon_emoji: str = ":robot_face:"):
    """
    Sends a simple message to Slack.
    """
    if not settings.SLACK_WEBHOOK_URL:
        return False

    headers = {'Content-type': 'application/json'}
    payload = {
        "text": message,
        "username": username,
        "icon_emoji": icon_emoji,
    }

    try:
        response = requests.post(settings.SLACK_WEBHOOK_URL, data=json.dumps(payload), headers=headers)
        response.raise_for_status()
        return True
    except Exception as e:
        print(f"Failed to send Slack notification: {e}")
        return False

def send_slack_report(title: str, report_data: dict):
    """
    Sends a comprehensive formatted report using Slack Blocks.
    """
    if not settings.SLACK_WEBHOOK_URL:
        return False

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🚀 {title}"
            }
        },
        {"type": "divider"}
    ]

    # 1. Performance Metrics Section
    if "metrics" in report_data:
        metrics_text = "*📈 Key Performance Metrics*\n"
        for m in report_data["metrics"]:
            metrics_text += f"• {m['label']}: `{m['value']}` ({m['change']})\n"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": metrics_text}})

    # 2. Sentiment & Trends Section
    if "sentiment" in report_data:
        sent = report_data["sentiment"]
        sent_text = f"*🔍 Sentiment & Trends*\n• Sentiment Score: `{sent['score']}/10`\n• Top Topics: {', '.join(sent['topics'])}\n• Viral Potential: `{sent['viral']}%`"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": sent_text}})

    # 3. A/B Testing Section
    if "ab_testing" in report_data:
        ab = report_data["ab_testing"]
        ab_text = "*🧪 Active A/B Tests Summary*\n"
        for test in ab:
            ab_text += f"• {test['name']}: {test['variantA']}% vs {test['variantB']}% ({test['status']})\n"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": ab_text}})

    # 4. Content Generation History
    if "content" in report_data:
        blocks.append({"type": "divider"})
        content_text = "*📝 Recent Content History*\n"
        for item in report_data["content"]:
            content_text += f"*[{item['platform']}]* {item['topic']} - Score: `{item['score']}/10`\n"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": content_text}})

    import datetime
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"Generated by TrendForgeAI on {now_str}"
            }
        ]
    })

    payload = {"blocks": blocks, "username": "TrendForgeAI Intelligence"}

    try:
        response = requests.post(settings.SLACK_WEBHOOK_URL, json=payload)
        response.raise_for_status()
        return True
    except Exception as e:
        print(f"Failed to send Slack report: {e}")
        return False
